# Generated by Django 5.2.6 on 2025-10-01 01:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expected_identificacion', models.CharField(blank=True, max_length=30)),
                ('used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80)),
                ('text', models.TextField()),
                ('help_text', models.TextField(blank=True)),
                ('qtype', models.CharField(choices=[('single', 'Opción única'), ('multi', 'Selección múltiple'), ('text', 'Texto'), ('int', 'Entero'), ('dec', 'Decimal'), ('bool', 'Sí/No'), ('date', 'Fecha'), ('likert', 'Likert (0..4)')], max_length=10)),
                ('required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('max_choices', models.PositiveIntegerField(default=0, help_text='0 = sin límite')),
            ],
            options={
                'ordering': ['section__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('require_token', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80)),
                ('label', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=1)),
                ('numeric_value', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.question')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('question', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ResponseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('identificacion', models.CharField(max_length=30)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('interviewer', models.CharField(blank=True, max_length=120)),
                ('source', models.CharField(blank=True, max_length=80)),
                ('device_fingerprint', models.CharField(blank=True, max_length=100)),
                ('zarit_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('zarit_category', models.CharField(choices=[('sin', 'Sin sobrecarga'), ('leve', 'Leve/Moderada'), ('intensa', 'Intensa')], default='sin', max_length=20)),
                ('access_token', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response', to='core.accesstoken')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='core.survey')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.section'),
        ),
        migrations.AddField(
            model_name='section',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.survey'),
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='core.survey'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True)),
                ('integer_answer', models.IntegerField(blank=True, null=True)),
                ('decimal_answer', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bool_answer', models.BooleanField(blank=True, null=True)),
                ('date_answer', models.DateField(blank=True, null=True)),
                ('options', models.ManyToManyField(blank=True, related_name='selected_in', to='core.option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='core.question')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.responseset')),
            ],
            options={
                'unique_together': {('response', 'question')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('section', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('survey', 'order')},
        ),
        migrations.AddIndex(
            model_name='responseset',
            index=models.Index(fields=['survey', 'identificacion'], name='core_respon_survey__5ff3a8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='responseset',
            unique_together={('survey', 'identificacion')},
        ),
    ]
