# Generated by Django 4.2 on 2025-10-03 05:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('document_number', models.CharField(max_length=30, unique=True)),
                ('document_type', models.CharField(choices=[('C.C', 'Cédula de Ciudadanía'), ('T.I', 'Tarjeta de Identidad'), ('R.E', 'Registro Civil'), ('C.E', 'Cédula de Extranjería'), ('NIT', 'Número de Identificación Tributaria'), ('PPT', 'Permiso por Protección Temporal'), ('PA', 'Pasaporte'), ('T.E', 'Tarjeta de Extranjería'), ('CD', 'Carnet Diplomático'), ('SP', 'Salvoconducto de Permanencia'), ('P.E.P', 'Permiso Especial de Permanencia')], max_length=5)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('require_token', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=1)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='surveys.survey')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('survey', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ResponseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=30)),
                ('document_type', models.CharField(choices=[('C.C', 'Cédula de Ciudadanía'), ('T.I', 'Tarjeta de Identidad'), ('R.E', 'Registro Civil'), ('C.E', 'Cédula de Extranjería'), ('NIT', 'Número de Identificación Tributaria'), ('PPT', 'Permiso por Protección Temporal'), ('PA', 'Pasaporte'), ('T.E', 'Tarjeta de Extranjería'), ('CD', 'Carnet Diplomático'), ('SP', 'Salvoconducto de Permanencia'), ('P.E.P', 'Permiso Especial de Permanencia')], max_length=5)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveys.interviewer')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='surveys.survey')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80)),
                ('text', models.TextField()),
                ('help_text', models.TextField(blank=True)),
                ('qtype', models.CharField(choices=[('single', 'Opción única'), ('multi', 'Selección múltiple'), ('text', 'Texto'), ('int', 'Entero'), ('dec', 'Decimal'), ('bool', 'Sí/No'), ('date', 'Fecha'), ('likert', 'Likert (0..4)')], default='text', max_length=10)),
                ('required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('max_choices', models.PositiveIntegerField(default=0, help_text='0 = sin límite')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.section')),
            ],
            options={
                'ordering': ['section__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80)),
                ('label', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=1)),
                ('numeric_value', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='surveys.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True)),
                ('integer_answer', models.IntegerField(blank=True, null=True)),
                ('decimal_answer', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bool_answer', models.BooleanField(blank=True, null=True)),
                ('date_answer', models.DateField(blank=True, null=True)),
                ('options', models.ManyToManyField(blank=True, related_name='selected_in', to='surveys.option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='surveys.question')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.responseset')),
            ],
        ),
        migrations.AddIndex(
            model_name='responseset',
            index=models.Index(fields=['survey', 'identificacion', 'document_type'], name='surveys_res_survey__46ea1c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='responseset',
            unique_together={('survey', 'identificacion', 'document_type')},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('section', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('question', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('response', 'question')},
        ),
    ]
