# Generated by Django 4.2 on 2025-10-07 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_survey_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='responseset',
            name='data_protection_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
