# Generated by Django 4.2 on 2025-10-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_survey_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='geojson_file',
            field=models.FileField(blank=True, null=True, upload_to='geojson_files/'),
        ),
        migrations.AddField(
            model_name='question',
            name='geojson_property_name',
            field=models.CharField(blank=True, help_text="Name of the property in GeoJSON features to use for choices (e.g., 'NOMBRE')", max_length=100, null=True),
        ),
    ]
