# Generated by Django 4.2 on 2025-10-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_barrio_geojsonfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarrioListFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('file', models.FileField(upload_to='barrio_list_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='GeoJSONFile',
        ),
        migrations.AlterModelOptions(
            name='barrio',
            options={'ordering': ['name'], 'verbose_name': 'Barrio', 'verbose_name_plural': 'Barrios'},
        ),
        migrations.RemoveField(
            model_name='barrio',
            name='geometry',
        ),
        migrations.RemoveField(
            model_name='question',
            name='geojson_file',
        ),
        migrations.RemoveField(
            model_name='question',
            name='geojson_property_name',
        ),
        migrations.AddField(
            model_name='answer',
            name='selected_barrios',
            field=models.ManyToManyField(blank=True, related_name='answers', to='surveys.barrio'),
        ),
        migrations.AddField(
            model_name='question',
            name='barrios',
            field=models.ManyToManyField(blank=True, related_name='questions', to='surveys.barrio'),
        ),
        migrations.AlterField(
            model_name='barrio',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='qtype',
            field=models.CharField(choices=[('single', 'Opción única'), ('multi', 'Selección múltiple'), ('text', 'Texto'), ('int', 'Entero'), ('dec', 'Decimal'), ('bool', 'Sí/No'), ('date', 'Fecha'), ('likert', 'Likert (0..4)'), ('barrio', 'Selección de Barrio(s)')], default='text', max_length=10),
        ),
    ]
