# Generated by Django 4.2 on 2025-10-08 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_responseset_data_protection_accepted'),
        ('surveys', '0005_barriolistfile_delete_geojsonfile_and_more'),
    ]

    operations = [
    ]
