# Generated by Django 4.2 on 2025-10-08 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_merge_20251007_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=255)),
                ('loc', models.CharField(max_length=255)),
                ('zona', models.CharField(max_length=255)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='surveys.municipio')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['municipio', 'nombre'],
                'unique_together': {('municipio', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='UbicacionListFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('file', models.FileField(upload_to='ubicacion_list_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BarrioListFile',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='selected_barrios',
        ),
        migrations.RemoveField(
            model_name='question',
            name='barrios',
        ),
        migrations.AlterField(
            model_name='question',
            name='qtype',
            field=models.CharField(choices=[('single', 'Opción única'), ('multi', 'Selección múltiple'), ('text', 'Texto'), ('int', 'Entero'), ('dec', 'Decimal'), ('bool', 'Sí/No'), ('date', 'Fecha'), ('likert', 'Likert (0..4)'), ('ubicacion', 'Selección de Ubicación')], default='text', max_length=10),
        ),
        migrations.DeleteModel(
            name='Barrio',
        ),
        migrations.AddField(
            model_name='answer',
            name='selected_ubicaciones',
            field=models.ManyToManyField(blank=True, related_name='answers', to='surveys.ubicacion'),
        ),
        migrations.AddField(
            model_name='question',
            name='ubicaciones',
            field=models.ManyToManyField(blank=True, related_name='questions', to='surveys.ubicacion'),
        ),
    ]
