# Generated by Django 5.0.14 on 2025-10-11 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_municipio_ubicacion_ubicacionlistfile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='copy_answer_from',
            field=models.ForeignKey(blank=True, help_text='Selecciona otra pregunta para copiar su respuesta.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copied_to', to='surveys.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='copy_answer_from_text',
            field=models.BooleanField(default=False, help_text='Si se marca, el texto de la pregunta se copiarÃ¡ de la pregunta seleccionada.'),
        ),
    ]
