# Generated by Django 4.2 on 2025-10-10 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_municipio_ubicacion_ubicacionlistfile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='single_choice_display',
            field=models.CharField(choices=[('radio', 'Botones de radio'), ('select', 'Lista desplegable')], default='radio', help_text='Solo para preguntas de opción única (single)', max_length=10),
        ),
    ]
