# Generated by Django 5.0.14 on 2025-10-11 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_question_copy_answer_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='copy_answer_from',
        ),
        migrations.RemoveField(
            model_name='question',
            name='copy_answer_from_text',
        ),
    ]
