# Generated by Django 4.2 on 2025-10-11 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_question_single_choice_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='depends_on',
            field=models.ForeignKey(blank=True, help_text='Mostrar esta pregunta solo si se selecciona esta opción en otra pregunta.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_questions', to='surveys.option'),
        ),
    ]
