# Generated by Django 4.2 on 2025-10-11 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_question_depends_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='depends_on_option',
            field=models.ForeignKey(blank=True, help_text='La opción que activa esta pregunta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggering_questions', to='surveys.option'),
        ),
        migrations.AlterField(
            model_name='question',
            name='depends_on',
            field=models.ForeignKey(blank=True, help_text='La pregunta de la que esta depende', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_questions', to='surveys.question'),
        ),
    ]
