# Generated by Django 4.2 on 2025-10-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0010_question_depends_on_option_alter_question_depends_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='depends_on_value_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor máximo para activar la pregunta (para respuestas numéricas)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='depends_on_value_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor mínimo para activar la pregunta (para respuestas numéricas)', max_digits=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(check=models.Q(('depends_on_option__isnull', True), models.Q(('depends_on_value_min__isnull', True), ('depends_on_value_max__isnull', True)), _connector='OR'), name='option_or_value_dependency'),
        ),
    ]
