# Generated by Django 5.0.14 on 2025-10-11 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0011_question_depends_on_value_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='copy_from',
            field=models.CharField(blank=True, help_text="Nombre del campo del cual copiar la respuesta (ej. 'identificacion' o 'question_123').", max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='copy_text_from',
            field=models.BooleanField(default=False, help_text='Si se marca, el texto de la pregunta se copiará del campo seleccionado.'),
        ),
    ]
