# Generated by Django 5.0.14 on 2025-10-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0012_question_copy_from_question_copy_text_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='max_value',
            field=models.IntegerField(blank=True, help_text='Valor máximo para preguntas de tipo entero.', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='min_value',
            field=models.IntegerField(blank=True, help_text='Valor mínimo para preguntas de tipo entero.', null=True),
        ),
    ]
