# Generated by Django 5.0.14 on 2025-10-14 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0013_question_max_value_question_min_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='other_option_trigger_code',
            field=models.CharField(blank=True, help_text="Para preguntas de opción única, si una opción con este código es seleccionada, se mostrará un campo de texto. (ej. 'otro')", max_length=80),
        ),
        migrations.AddField(
            model_name='question',
            name='other_text_label',
            field=models.CharField(blank=True, default='Especifique', help_text="Etiqueta para el campo de texto 'otro'.", max_length=100),
        ),
    ]
