# Generated by Django 5.0.14 on 2025-10-14 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0014_question_other_option_trigger_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='other_option_trigger_code',
        ),
        migrations.AddField(
            model_name='option',
            name='is_other_trigger',
            field=models.BooleanField(default=False, help_text='Si se marca, esta opción mostrará un campo de texto adicional.', verbose_name="Es la opción 'Otro'"),
        ),
    ]
