# Generated by Django 4.2 on 2025-10-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0015_remove_question_other_option_trigger_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responseset',
            name='phone',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
