# Generated by Django 4.2 on 2025-10-17 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0016_alter_responseset_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responseset',
            name='full_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
